- .eslintrc
- .gitignore
- CHANGELOG.md
- CONTRIBUTING.md
- Jenkinsfile
- LICENSE
- README.md
- src/index.js
- src/settings/GeneralSettings.js
- src/settings/index.js
- test/bigtest/.eslintrc.js
- test/bigtest/helpers/setup-application.js
- test/bigtest/index.js
- test/bigtest/interactors/application.js
- test/bigtest/interactors/example-page.js
- test/bigtest/interactors/settings.js
- test/bigtest/network/boot.js
- test/bigtest/network/config.js
- test/bigtest/network/index.js
- test/bigtest/network/scenarios/default.js
- test/bigtest/tests/settings-test.js
- translations/ui-oai-pmh/en.json
Add UI module for OAI-PMH feature
> MODOAIPMH-94: add ui module oai-pmh.

- translations/ui-oai-pmh/ar.json
- translations/ui-oai-pmh/ca.json
- translations/ui-oai-pmh/da.json
- translations/ui-oai-pmh/de.json
- translations/ui-oai-pmh/en_GB.json
- translations/ui-oai-pmh/en_SE.json
- translations/ui-oai-pmh/en_US.json
- translations/ui-oai-pmh/es.json
- translations/ui-oai-pmh/es_419.json
- translations/ui-oai-pmh/es_ES.json
- translations/ui-oai-pmh/fr.json
- translations/ui-oai-pmh/fr_FR.json
- translations/ui-oai-pmh/he.json
- translations/ui-oai-pmh/hu.json
- translations/ui-oai-pmh/it_IT.json
- translations/ui-oai-pmh/ja.json
- translations/ui-oai-pmh/pt_BR.json
- translations/ui-oai-pmh/pt_PT.json
- translations/ui-oai-pmh/ru.json
- translations/ui-oai-pmh/ur.json
- translations/ui-oai-pmh/zh_CN.json
- translations/ui-oai-pmh/zh_TW.json
> Update translation strings as of 20200331T152557

- Jenkinsfile
Add add UI module for OAI-PMH
https://issues.folio.org/browse/MODOAIPMH-94
> MODOAIPMH-94: change Jenkinsfile setting

- package.json
Integrate front-end with back-end to manipulate OAI-PMH settings
https://issues.folio.org/browse/MODOAIPMH-110
> MODOAIPMH-110: fix oai-pmh permission.

- translations/ui-oai-pmh/ar.json
- translations/ui-oai-pmh/ca.json
- translations/ui-oai-pmh/da.json
- translations/ui-oai-pmh/de.json
- translations/ui-oai-pmh/en_GB.json
- translations/ui-oai-pmh/en_SE.json
- translations/ui-oai-pmh/en_US.json
- translations/ui-oai-pmh/es.json
- translations/ui-oai-pmh/es_419.json
- translations/ui-oai-pmh/es_ES.json
- translations/ui-oai-pmh/fr.json
- translations/ui-oai-pmh/fr_FR.json
- translations/ui-oai-pmh/he.json
- translations/ui-oai-pmh/hu.json
- translations/ui-oai-pmh/it_IT.json
- translations/ui-oai-pmh/ja.json
- translations/ui-oai-pmh/pt_BR.json
- translations/ui-oai-pmh/pt_PT.json
- translations/ui-oai-pmh/ru.json
- translations/ui-oai-pmh/ur.json
- translations/ui-oai-pmh/zh_CN.json
- translations/ui-oai-pmh/zh_TW.json
> Update translation strings as of 20200416T214343

- package.json
- translations/ui-oai-pmh/en.json
Integrate front-end with back-end to manipulate OAI-PMH settings
https://issues.folio.org/browse/MODOAIPMH-110
> MODOAIPMH-110: fix translations for oai-pmh permission.

- translations/ui-oai-pmh/ar.json
- translations/ui-oai-pmh/ca.json
- translations/ui-oai-pmh/da.json
- translations/ui-oai-pmh/de.json
- translations/ui-oai-pmh/en_GB.json
- translations/ui-oai-pmh/en_SE.json
- translations/ui-oai-pmh/en_US.json
- translations/ui-oai-pmh/es.json
- translations/ui-oai-pmh/es_419.json
- translations/ui-oai-pmh/es_ES.json
- translations/ui-oai-pmh/fr.json
- translations/ui-oai-pmh/fr_FR.json
- translations/ui-oai-pmh/he.json
- translations/ui-oai-pmh/hu.json
- translations/ui-oai-pmh/it_IT.json
- translations/ui-oai-pmh/ja.json
- translations/ui-oai-pmh/pt_BR.json
- translations/ui-oai-pmh/pt_PT.json
- translations/ui-oai-pmh/ru.json
- translations/ui-oai-pmh/ur.json
- translations/ui-oai-pmh/zh_CN.json
- translations/ui-oai-pmh/zh_TW.json
> Update translation strings as of 20200420T134821

- translations/ui-oai-pmh/ja.json
> Update translation strings as of 20200421T180634

- translations/ui-oai-pmh/es_419.json
- translations/ui-oai-pmh/zh_TW.json
> Update translation strings as of 20200423T142657

- CHANGELOG.md
- src/settings/BehaviorForm.js
- src/settings/GeneralForm.js
- src/settings/TechnicalForm.js
- src/settings/components/DefaultValidators.js
- src/settings/components/FormValidator.js
- src/settings/components/GeneralFormValidator.js
- src/settings/components/RowComponent.js
- src/settings/components/TechnicalFormValidator.js
- src/settings/components/index.js
- test/bigtest/interactors/settings.js
- test/bigtest/tests/settings-test.js
- translations/ui-oai-pmh/en.json
Perform validation for OAI-PMH settings
https://issues.folio.org/browse/MODOAIPMH-111
> MODOAIPMH-111: perform validation for OAI-PMH settings.

- translations/ui-oai-pmh/ar.json
- translations/ui-oai-pmh/ca.json
- translations/ui-oai-pmh/da.json
- translations/ui-oai-pmh/de.json
- translations/ui-oai-pmh/en_GB.json
- translations/ui-oai-pmh/en_SE.json
- translations/ui-oai-pmh/en_US.json
- translations/ui-oai-pmh/es.json
- translations/ui-oai-pmh/es_419.json
- translations/ui-oai-pmh/es_ES.json
- translations/ui-oai-pmh/fr.json
- translations/ui-oai-pmh/fr_FR.json
- translations/ui-oai-pmh/he.json
- translations/ui-oai-pmh/hu.json
- translations/ui-oai-pmh/it_IT.json
- translations/ui-oai-pmh/ja.json
- translations/ui-oai-pmh/pt_BR.json
- translations/ui-oai-pmh/pt_PT.json
- translations/ui-oai-pmh/ru.json
- translations/ui-oai-pmh/ur.json
- translations/ui-oai-pmh/zh_CN.json
- translations/ui-oai-pmh/zh_TW.json
> Update translation strings as of 20200505T210535

- translations/ui-oai-pmh/fr_FR.json
> Update translation strings as of 20200519T123842

- translations/ui-oai-pmh/fr_FR.json
> Update translation strings as of 20200602T151309

- translations/ui-oai-pmh/fr_FR.json
> Update translation strings as of 20200604T202430

- CHANGELOG.md
- package.json
Update to Stripes v4
https://issues.folio.org/browse/MODOAIPMH-132
> Update to Stripes v4. Refs MODOAIPMH-132

- CHANGELOG.md
Add icon to OAI-PMH settings
https://issues.folio.org/browse/MODOAIPMH-171
#Depend on 
https://github.com/folio-org/ui-oai-pmh/pull/28
> MODOAIPMH-171: add icon to OAI-PMH settings

- translations/ui-oai-pmh/ru.json
> Update translation strings as of 20200624T182544

- translations/ui-oai-pmh/ru.json
> Update translation strings as of 20200626T180122

- CHANGELOG.md
- src/settings/components/DefaultValidators.js
- src/settings/components/TechnicalFormValidator.js
- translations/ui-oai-pmh/en.json
Add Validate for Max records per response value
https://issues.folio.org/browse/UIOAIPMH-14
> UIOAIPMH-14: add Validate for Max records per response value

- translations/ui-oai-pmh/ar.json
- translations/ui-oai-pmh/ca.json
- translations/ui-oai-pmh/da.json
- translations/ui-oai-pmh/de.json
- translations/ui-oai-pmh/en_GB.json
- translations/ui-oai-pmh/en_SE.json
- translations/ui-oai-pmh/en_US.json
- translations/ui-oai-pmh/es.json
- translations/ui-oai-pmh/es_419.json
- translations/ui-oai-pmh/es_ES.json
- translations/ui-oai-pmh/fr.json
- translations/ui-oai-pmh/fr_FR.json
- translations/ui-oai-pmh/he.json
- translations/ui-oai-pmh/hu.json
- translations/ui-oai-pmh/it_IT.json
- translations/ui-oai-pmh/ja.json
- translations/ui-oai-pmh/pt_BR.json
- translations/ui-oai-pmh/pt_PT.json
- translations/ui-oai-pmh/ru.json
- translations/ui-oai-pmh/ur.json
- translations/ui-oai-pmh/zh_CN.json
- translations/ui-oai-pmh/zh_TW.json
> Update translation strings as of 20200707T213422

- translations/ui-oai-pmh/ar.json
- translations/ui-oai-pmh/ca.json
- translations/ui-oai-pmh/da.json
- translations/ui-oai-pmh/de.json
- translations/ui-oai-pmh/en_GB.json
- translations/ui-oai-pmh/en_SE.json
- translations/ui-oai-pmh/en_US.json
- translations/ui-oai-pmh/es.json
- translations/ui-oai-pmh/es_419.json
- translations/ui-oai-pmh/es_ES.json
- translations/ui-oai-pmh/fr.json
- translations/ui-oai-pmh/fr_FR.json
- translations/ui-oai-pmh/he.json
- translations/ui-oai-pmh/hu.json
- translations/ui-oai-pmh/it_IT.json
- translations/ui-oai-pmh/ja.json
- translations/ui-oai-pmh/pt_BR.json
- translations/ui-oai-pmh/pt_PT.json
- translations/ui-oai-pmh/ru.json
- translations/ui-oai-pmh/ur.json
- translations/ui-oai-pmh/zh_CN.json
- translations/ui-oai-pmh/zh_TW.json
> Update translation strings as of 20200710T132222

- CHANGELOG.md
- package.json
- src/settings/components/Sets/SetsView/SetsView.js
- src/settings/components/Sets/SetsView/common/ActionItem/ActionItem.css
- src/settings/components/Sets/SetsView/common/ActionItem/ActionItem.js
- src/settings/components/Sets/SetsView/common/ActionItem/index.js
- src/settings/constants/base.js
- src/settings/constants/sets.js
- src/settings/routes/sets/SetsCreateRoute.js
- src/settings/routes/sets/SetsEditRoute.js
- src/settings/routes/sets/SetsViewRoute.js
- test/bigtest/interactors/sets-view.js
- test/bigtest/network/index.js
- test/bigtest/network/scenarios/success-delete.js
- test/bigtest/tests/sets/create-edit-test.js
- test/bigtest/tests/sets/view-test.js
- translations/ui-oai-pmh/en.json
Delete existing OAI-PMH set
https://issues.folio.org/browse/UIOAIPMH-11
> UIOAIPMH-11: add ability for delete existing set

- translations/ui-oai-pmh/ar.json
- translations/ui-oai-pmh/ca.json
- translations/ui-oai-pmh/da.json
- translations/ui-oai-pmh/de.json
- translations/ui-oai-pmh/en_GB.json
- translations/ui-oai-pmh/en_SE.json
- translations/ui-oai-pmh/en_US.json
- translations/ui-oai-pmh/es.json
- translations/ui-oai-pmh/es_419.json
- translations/ui-oai-pmh/es_ES.json
- translations/ui-oai-pmh/fr.json
- translations/ui-oai-pmh/fr_FR.json
- translations/ui-oai-pmh/he.json
- translations/ui-oai-pmh/hu.json
- translations/ui-oai-pmh/it_IT.json
- translations/ui-oai-pmh/ja.json
- translations/ui-oai-pmh/pt_BR.json
- translations/ui-oai-pmh/pt_PT.json
- translations/ui-oai-pmh/ru.json
- translations/ui-oai-pmh/ur.json
- translations/ui-oai-pmh/zh_CN.json
- translations/ui-oai-pmh/zh_TW.json
> Update translation strings as of 20200806T130626

- src/settings/components/Sets/SetsView/SetsView.js
- src/settings/constants/base.js
- src/settings/routes/index.js
- src/settings/routes/sets/SetsCreateRoute.js
- src/settings/routes/sets/SetsDuplicateRoute.js
- src/settings/routes/sets/SetsViewRoute.js
- src/settings/routes/sets/index.js
- src/settings/util/convertData.js
- src/settings/util/route.js
- test/bigtest/interactors/sets-view.js
- test/bigtest/tests/sets/create-edit-test.js
- test/bigtest/tests/sets/create-test.js
- test/bigtest/tests/sets/duplicate-test.js
- test/bigtest/tests/sets/view-test.js
- translations/ui-oai-pmh/en.json
Duplicate OAI-PMH set
https://issues.folio.org/browse/UIOAIPMH-8
> UIOAIPMH-8: add ability for duplicate set

- translations/ui-oai-pmh/ar.json
- translations/ui-oai-pmh/ca.json
- translations/ui-oai-pmh/da.json
- translations/ui-oai-pmh/de.json
- translations/ui-oai-pmh/en_GB.json
- translations/ui-oai-pmh/en_SE.json
- translations/ui-oai-pmh/en_US.json
- translations/ui-oai-pmh/es.json
- translations/ui-oai-pmh/es_419.json
- translations/ui-oai-pmh/es_ES.json
- translations/ui-oai-pmh/fr.json
- translations/ui-oai-pmh/fr_FR.json
- translations/ui-oai-pmh/he.json
- translations/ui-oai-pmh/hu.json
- translations/ui-oai-pmh/it_IT.json
- translations/ui-oai-pmh/ja.json
- translations/ui-oai-pmh/pt_BR.json
- translations/ui-oai-pmh/pt_PT.json
- translations/ui-oai-pmh/ru.json
- translations/ui-oai-pmh/ur.json
- translations/ui-oai-pmh/zh_CN.json
- translations/ui-oai-pmh/zh_TW.json
> Update translation strings as of 20200807T145751

- CHANGELOG.md
- src/settings/routes/sets/SetsCreateRoute.js
- src/settings/routes/sets/SetsDuplicateRoute.js
- src/settings/routes/sets/SetsEditRoute.js
- src/settings/routes/sets/SetsViewRoute.js
- test/bigtest/network/config.js
- test/bigtest/network/scenarios/sets-not-found.js
- test/bigtest/network/scenarios/success-delete.js
Rename sets endpoints
https://issues.folio.org/browse/UIOAIPMH-16
> UIOAIPMH-16: rename sets endpoints

- translations/ui-oai-pmh/ar.json
- translations/ui-oai-pmh/ca.json
- translations/ui-oai-pmh/da.json
- translations/ui-oai-pmh/de.json
- translations/ui-oai-pmh/en_GB.json
- translations/ui-oai-pmh/en_SE.json
- translations/ui-oai-pmh/en_US.json
- translations/ui-oai-pmh/es.json
- translations/ui-oai-pmh/es_419.json
- translations/ui-oai-pmh/es_ES.json
- translations/ui-oai-pmh/fr.json
- translations/ui-oai-pmh/fr_FR.json
- translations/ui-oai-pmh/he.json
- translations/ui-oai-pmh/hu.json
- translations/ui-oai-pmh/it_IT.json
- translations/ui-oai-pmh/ja.json
- translations/ui-oai-pmh/pt_BR.json
- translations/ui-oai-pmh/pt_PT.json
- translations/ui-oai-pmh/ru.json
- translations/ui-oai-pmh/ur.json
- translations/ui-oai-pmh/zh_CN.json
- translations/ui-oai-pmh/zh_TW.json
> Update translation strings as of 20200901T173106

- CHANGELOG.md
- package.json
Update project peer-dependency for react-intl
https://issues.folio.org/browse/UIOAIPMH-20
> UIOAIPMH-20: Update react-intl to ^5.7.0

- CHANGELOG.md
- src/settings/components/Sets/SetsForm/SetsForm.js
- src/settings/components/Sets/SetsList/SetsList.js
- src/settings/components/Sets/SetsList/components/LastMenu.js
- src/settings/components/Sets/SetsView/components/FilteringConditions/FilteringConditions.js
- src/settings/components/common/SaveButtonTooltipWrapper.js
- src/settings/constants/base.js
- src/settings/routes/sets/SetsListRoute.js
- test/bigtest/interactors/sets-list.js
- test/bigtest/network/config.js
- test/bigtest/tests/sets/create-edit-test.js
- test/bigtest/tests/sets/create-list-test.js
- translations/ui-oai-pmh/en.json
Add set list
https://issues.folio.org/browse/UIOAIPMH-9
> UIOAIPMH-9: add set list

- package.json
Add permission for set list
https://issues.folio.org/browse/UIOAIPMH-9
> UIOAIPMH-9: add permission for set list

- CHANGELOG.md
- src/settings/constants/base.js
- src/settings/routes/sets/SetsCreateRoute.js
- src/settings/routes/sets/SetsDuplicateRoute.js
- src/settings/routes/sets/SetsEditRoute.js
- src/settings/util/connectionProblem.js
- src/settings/util/convertData.js
- src/settings/util/index.js
- test/bigtest/network/scenarios/save-error.js
- test/bigtest/tests/sets/create-edit-test.js
- translations/ui-oai-pmh/en.json
Add validation for uniqueness
https://issues.folio.org/browse/UIOAIPMH-18
> UIOAIPMH-18: add validation for uniqueness.

- translations/ui-oai-pmh/ar.json
- translations/ui-oai-pmh/ca.json
- translations/ui-oai-pmh/da.json
- translations/ui-oai-pmh/de.json
- translations/ui-oai-pmh/en_GB.json
- translations/ui-oai-pmh/en_SE.json
- translations/ui-oai-pmh/en_US.json
- translations/ui-oai-pmh/es.json
- translations/ui-oai-pmh/es_419.json
- translations/ui-oai-pmh/es_ES.json
- translations/ui-oai-pmh/fr.json
- translations/ui-oai-pmh/fr_FR.json
- translations/ui-oai-pmh/he.json
- translations/ui-oai-pmh/hu.json
- translations/ui-oai-pmh/it_IT.json
- translations/ui-oai-pmh/ja.json
- translations/ui-oai-pmh/pt_BR.json
- translations/ui-oai-pmh/pt_PT.json
- translations/ui-oai-pmh/ru.json
- translations/ui-oai-pmh/ur.json
- translations/ui-oai-pmh/zh_CN.json
- translations/ui-oai-pmh/zh_TW.json
> Update translation strings as of 20200910T134908

- translations/ui-oai-pmh/ja.json
> Update translation strings as of 20200914T140557

- CHANGELOG.md
- package.json
- src/settings/components/Sets/SetsList/SetsList.js
- src/settings/components/Sets/SetsView/SetsView.js
- src/settings/constants/base.js
- src/settings/hooks/index.js
- src/settings/hooks/useLocationReset.js
- src/settings/routes/index.js
- src/settings/routes/sets/SetsCreateRoute.js
- src/settings/routes/sets/SetsDuplicateRoute.js
- src/settings/routes/sets/SetsEditRoute.js
- src/settings/routes/sets/SetsListRoute.js
- src/settings/routes/sets/SetsRootLayer.js
- src/settings/routes/sets/SetsViewRoute.js
- test/bigtest/interactors/sets-list.js
Show set details next to the list of sets
https://issues.folio.org/browse/UIOAIPMH-25
> UIOAIPMH-25: Show set details next to the list of sets

- CHANGELOG.md
- package.json
Update stripes to v5
https://issues.folio.org/browse/UIOAIPMH-28
> UIOAIPMH-28: Update stripes to v5

- translations/ui-oai-pmh/pt_BR.json
> Update translation strings as of 20200922T125348

- CHANGELOG.md
- package.json
- src/settings/components/Sets/SetsForm/SetsForm.js
- src/settings/components/Sets/SetsForm/components/FilteringConditions/components/FilteringConditionsName/FilteringConditionsName.js
- src/settings/components/Sets/SetsForm/components/GeneralInformation/GeneralInformation.js
- src/settings/components/Sets/SetsForm/components/GeneralInformation/components/SetSpecification/SetSpecification.css
- src/settings/components/Sets/SetsForm/components/GeneralInformation/components/SetSpecification/SetSpecification.js
- src/settings/components/Sets/SetsForm/components/GeneralInformation/components/SetSpecification/index.js
- src/settings/components/Sets/SetsForm/components/GeneralInformation/components/index.js
- src/settings/components/Sets/common/EntityNotFound.js
- src/settings/util/convertData.js
- src/settings/util/filteringConditionsDataOptions.js
- test/bigtest/interactors/sets-form.js
- test/bigtest/network/factories/set.js
- test/bigtest/tests/sets/create-edit-test.js
- test/bigtest/tests/sets/create-list-test.js
- test/bigtest/tests/sets/view-test.js
- translations/ui-oai-pmh/en.json
Preview set specification on create/edit page
https://issues.folio.org/browse/UIOAIPMH-21
> UIOAIPMH-21: add set spec specification on create/edit page

- translations/ui-oai-pmh/fr_FR.json
> Update translation strings as of 20201005T202004

- CHANGELOG.md
- package.json
Release v2.0.0 in the scope of the [UIOAIPMH-37](https://issues.folio.org/browse/UIOAIPMH-37).
> UIOAIPMH-37: Release v2.0.0

- CHANGELOG.md
- package.json
Release v2.1.0 in the scope of the [UIOAIPMH-42](https://issues.folio.org/browse/UIOAIPMH-42).
> UIOAIPMH-42: Release v2.1.0

- CHANGELOG.md
- src/settings/components/Sets/SetsList/SetLits.test.js
- src/settings/routes/sets/SetsCreateRoute.js
- src/settings/routes/sets/SetsDuplicateRoute.js
- src/settings/routes/sets/SetsEditRoute.js
- src/settings/routes/sets/SetsRootLayer.js
- src/settings/routes/sets/SetsViewRoute.js
- test/jest/babel.config.js
https://issues.folio.org/browse/UIOAIPMH-41
While it's helpful for reviewers to help …
> UIOAIPMH-41: prefer @folio/stripes exports to private paths when importing components

- CHANGELOG.md
- Jenkinsfile
- package.json
Purpose: https://issues.folio.org/browse/UIOAIPMH-40
> UIOAIPMH-40 Compile Translation Files into AST Format

- .eslintrc
- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIOAIPMH-49
While it's helpful for reviewers to help …
> Release v3.2.0

- CHANGELOG.md
- package.json
- src/settings/components/Behavior/Behavior.js
https://issues.folio.org/browse/UIOAIPMH-53
While it's helpful for reviewers to help …
> UIOAIPMH-53 Set default settings for OAI-PMH in FOLIO

- CHANGELOG.md
- src/settings/components/Behavior/Behavior.js
- src/settings/components/Behavior/components/BehaviorForm.js
- src/settings/components/Behavior/components/BehaviorForm.test.js
- translations/ui-oai-pmh/en.json
- translations/ui-oai-pmh/en_GB.json
- translations/ui-oai-pmh/en_US.json
[UIOAIPMH-22](https://issues.folio.org/browse/UIOAIPMH-22)
While it's helpful for reviewers …
> UIOAIPMH-22: Expand OAI-PMH Behavior settings with Records Source parameter

- CHANGELOG.md
- src/OaiPmh.test.js
- src/settings/OaiPmhSettings.test.js
- src/settings/index.js
- src/settings/util/route.test.js
- test/jest/__mock__/stripesSmartComponents.mock.js
Reason: https://issues.folio.org/browse/UIOAIPMH-62
> UIOAIPMH-62 Hide Sets configuration option in Settings->OAI-PMH

- CHANGELOG.md
- src/settings/components/Behavior/components/BehaviorForm.js
https://issues.folio.org/browse/UIOAIPMH-66
> UIOAIPMH-66 Disable 'Inventory' records source

- .eslintrc
- package.json
- src/index.js
- src/settings/components/Logs/Logs.js
- src/settings/components/Logs/Logs.test.js
- src/settings/components/Logs/index.js
- src/settings/components/Sets/SetsList/SetLits.test.js
- src/settings/components/index.js
- src/settings/constants/columns.js
- src/settings/constants/index.js
- src/settings/constants/logs.js
- src/settings/hooks/useLogs.js
- src/settings/index.js
- src/settings/util/formatters.js
- translations/ui-oai-pmh/en.json
Add logs tab in OAI-PMH settings
https://issues.folio.org/browse/UIOAIPMH-67
> UIOAIPMH-67 Display list of recently run harvests

- CHANGELOG.md
- src/OaiPmh.test.js
- src/settings/OaiPmhSettings.test.js
- src/settings/index.js
- translations/ui-oai-pmh/en.json
[UIOAIPMH-71](https://issues.folio.org/browse/UIOAIPMH-71)
While it's helpful for reviewers …
> UIOAIPMH-71: OAI-PMH settings: Ensure your settings HTML page title follow this format - <<App name>> settings - <<selected page name>> - FOLIO

- CHANGELOG.md
- package.json
- src/settings/components/Behavior/Behavior.test.js
- src/settings/components/Behavior/components/BehaviorForm.test.js
- src/settings/components/General/General.test.js
- src/settings/components/General/components/GeneralForm.test.js
- src/settings/components/Logs/Logs.test.js
- src/settings/components/Sets/SetsForm/SetsForm.test.js
- src/settings/components/Sets/SetsList/SetLits.test.js
- src/settings/components/Sets/SetsView/SetsView.test.js
- src/settings/components/Sets/common/EntityNotFound.test.js
- src/settings/components/Technical/Techincal.test.js
- src/settings/components/Technical/components/TechnicalForm.test.js
- test/jest/__mock__/index.js
- test/jest/__mock__/resizeObserver.mock.js
https://folio-org.atlassian.net/browse/UIOAIPMH-80
Here we added accessibility aXe tests to existing jest test cases
> UIOAIPMH-80: OAI-PMH - Add accessibility testing to automated tests

- CHANGELOG.md
- package.json
- src/settings/components/common/RowComponent.js
https://folio-org.atlassian.net/browse/UIOAIPMH-81
> Release v5.1.0

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UIOAIPMH-88
> UIOAIPMH-88 cleanup module descriptor for ui-oai-pmh
